CREATE TABLE IF NOT EXISTS staging_postos (
  id BIGSERIAL PRIMARY KEY,
  importacao_id BIGINT NOT NULL REFERENCES importacoes(id) ON DELETE CASCADE,
  linha_origem INTEGER NOT NULL,
  cnpj TEXT,
  nome_posto TEXT,
  nome_fantasia TEXT,
  bandeira TEXT,
  logradouro TEXT,
  numero TEXT,
  complemento TEXT,
  bairro TEXT,
  municipio TEXT,
  uf TEXT,
  cep TEXT,
  cpf_responsavel TEXT,
  nome_responsavel TEXT,
  email_responsavel TEXT,
  cargo_responsavel TEXT,
  combustiveis TEXT,
  status TEXT,
  data_inauguracao TEXT,
  numero_bicos TEXT,
  numero_pistas TEXT,
  observacoes TEXT,
  valido BOOLEAN NOT NULL DEFAULT TRUE,
  erro_validacao TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
